# Generated by Django 4.2.19 on 2025-07-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perspectives', '0004_perspectiveitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspectiveitem',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=20),
        ),
    ]
