# Generated by Django 4.2.19 on 2025-07-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perspectives', '0005_alter_perspectiveitem_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspectiveitem',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('enum', 'Enum')], max_length=20),
        ),
    ]
