# Generated by Django 4.2.19 on 2025-07-03 23:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_annotationrulegrid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perspectives', '0011_alter_adminperspective_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminperspective',
            unique_together={('project', 'user')},
        ),
    ]
